#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
Created on March 7, 2014

@author: Chunwei Yan @ PKU
@mail:  yanchunwei@outlook.com

train the autoencoder to merge the word vectors generated by word2vec,
and finally generate the sentence vector.
'''
from __future__ import division

class SyntaxTreeAutoencoder(object):
    def __init__(self):
        pass

    def _init(self):
        pass


if __name__ == "__main__":
    pass

